# Generated by Django 5.2.5 on 2025-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryId', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryTitle', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('recipeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('tag', models.ManyToManyField(db_column='categoryTitle', to='recipesMain.category')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
