# Generated by Django 5.2.5 on 2025-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Penis'),
            preserve_default=False,
        ),
    ]
