# Generated by Django 5.2.5 on 2025-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='food_images/icon.png', upload_to='food_images'),
        ),
    ]
