# Generated by Django 5.2.5 on 2025-11-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0003_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientTable',
            fields=[
                ('ingredientId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'ingredientTable',
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='food_images/icon.png', upload_to='food_images/'),
        ),
    ]
