# Generated by Django 5.2.5 on 2025-11-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0004_ingredienttable_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientRelations',
            fields=[
                ('relationId', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=100)),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesMain.ingredienttable')),
                ('recpieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesMain.recipe')),
            ],
            options={
                'db_table': 'ingredientRelations',
            },
        ),
    ]
