# Generated by Django 5.2.5 on 2025-11-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0005_ingredientrelations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookTime',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prepTime',
            field=models.IntegerField(default=15),
        ),
        migrations.CreateModel(
            name='instructions',
            fields=[
                ('instructionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('stepNumber', models.IntegerField()),
                ('stepBody', models.TextField(max_length=300)),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesMain.recipe')),
            ],
            options={
                'db_table': 'instructions',
            },
        ),
    ]
