# Generated by Django 5.2.5 on 2025-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0006_recipe_cooktime_recipe_preptime_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrelations',
            name='ingredientId',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ingredientTable',
        ),
    ]
