# Generated by Django 5.2.5 on 2025-11-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesMain', '0007_alter_ingredientrelations_ingredientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrelations',
            old_name='ingredientId',
            new_name='ingredient',
        ),
    ]
